const items = [
    {
      id: 1,
      title: "煮卵",
      price: "1200",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 2,
      title: "ソーセージ",
      price: "2400",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 3,
      title: "カーディガン",
      price: "8900",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 4,
      title: "神戸牛",
      price: "10000",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 5,
      title: "いなり",
      price: "1000",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 6,
      title: "なす",
      price: "1200",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 7,
      title: "竿",
      price: "1500",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 8,
      title: "パソコン",
      price: "40000",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 9,
      title: "エリンギ",
      price: "1800",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 10,
      title: "シャツ",
      price: "3000",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 11,
      title: "味噌",
      price: "300",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 12,
      title: "ジャケット",
      price: "30000",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 13,
      title: "おせち",
      price: "7000",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 14,
      title: "マグロ",
      price: "4000",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
    {
      id: 15,
      title: "兜",
      price: "47000",
      img: "https://source.unsplash.com/random",
      amount: 0,
    },
  ];
  
  export default items;